name: JS tests
on: [push, pull_request]
jobs:
    js-linter:
        name: JS linter
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-versions: [ '12', '13', '14' ]
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-versions }}
            - run: npm install
            - name: Lint
              run: npm run lint
