name: JS tests
on: [push, pull_request]
jobs:
    js-linter:
        name: JS linter
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # PS 8.2 : Node 16
                # PS 9.1 : Node 20
                # PS 9.2 : Node 20
                node-versions: [ '16', '20' ]
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-versions }}
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint
